//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.15 at 08:59:21 AM CEST 
//


package com.orange.mmp.bind.data.mobile;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mobile-catalog element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="mobile-catalog">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="mobile" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="jadAttributes" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="jadAction" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="action" use="required">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="add"/>
 *                                             &lt;enumeration value="modify"/>
 *                                             &lt;enumeration value="delete"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="inJad">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="signed"/>
 *                                             &lt;enumeration value="unsigned"/>
 *                                             &lt;enumeration value="always"/>
 *                                             &lt;enumeration value="never"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="inMF">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="signed"/>
 *                                             &lt;enumeration value="unsigned"/>
 *                                             &lt;enumeration value="always"/>
 *                                             &lt;enumeration value="never"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                       &lt;attribute name="strict" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                                       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="dropped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="dropDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="OTAEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                   &lt;attribute name="branchId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="codeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="finalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="midletType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="shortUA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="userAgentKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mobile"
})
@XmlRootElement(name = "mobile-catalog")
public class MobileCatalog {

    @XmlElement(required = true)
    protected List<Mobile> mobile;

    /**
     * Gets the value of the mobile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mobile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMobile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mobile }
     * 
     * 
     */
    public List<Mobile> getMobile() {
        if (mobile == null) {
            mobile = new ArrayList<Mobile>();
        }
        return this.mobile;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="jadAttributes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="jadAction" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="action" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="add"/>
     *                                 &lt;enumeration value="modify"/>
     *                                 &lt;enumeration value="delete"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="inJad">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="signed"/>
     *                                 &lt;enumeration value="unsigned"/>
     *                                 &lt;enumeration value="always"/>
     *                                 &lt;enumeration value="never"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="inMF">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="signed"/>
     *                                 &lt;enumeration value="unsigned"/>
     *                                 &lt;enumeration value="always"/>
     *                                 &lt;enumeration value="never"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="strict" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="dropped" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="dropDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="OTAEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="branchId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="codeName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="finalName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="midletType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="shortUA" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="userAgentKey" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jadAttributes",
        "dropped",
        "dropDate"
    })
    public static class Mobile {

        protected JadAttributes jadAttributes;
        protected boolean dropped;
        protected String dropDate;
        @XmlAttribute(name = "OTAEnabled")
        protected Boolean otaEnabled;
        @XmlAttribute
        protected String branchId;
        @XmlAttribute
        protected String codeName;
        @XmlAttribute(required = true)
        protected String finalName;
        @XmlAttribute(required = true)
        protected String midletType;
        @XmlAttribute(required = true)
        protected String shortUA;
        @XmlAttribute(required = true)
        protected String userAgentKey;

        /**
         * Gets the value of the jadAttributes property.
         * 
         * @return
         *     possible object is
         *     {@link JadAttributes }
         *     
         */
        public JadAttributes getJadAttributes() {
            return jadAttributes;
        }

        /**
         * Sets the value of the jadAttributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link JadAttributes }
         *     
         */
        public void setJadAttributes(JadAttributes value) {
            this.jadAttributes = value;
        }

        /**
         * Gets the value of the dropped property.
         * 
         */
        public boolean isDropped() {
            return dropped;
        }

        /**
         * Sets the value of the dropped property.
         * 
         */
        public void setDropped(boolean value) {
            this.dropped = value;
        }

        /**
         * Gets the value of the dropDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDropDate() {
            return dropDate;
        }

        /**
         * Sets the value of the dropDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDropDate(String value) {
            this.dropDate = value;
        }

        /**
         * Gets the value of the otaEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isOTAEnabled() {
            return otaEnabled;
        }

        /**
         * Sets the value of the otaEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOTAEnabled(Boolean value) {
            this.otaEnabled = value;
        }

        /**
         * Gets the value of the branchId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBranchId() {
            return branchId;
        }

        /**
         * Sets the value of the branchId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBranchId(String value) {
            this.branchId = value;
        }

        /**
         * Gets the value of the codeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodeName() {
            return codeName;
        }

        /**
         * Sets the value of the codeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodeName(String value) {
            this.codeName = value;
        }

        /**
         * Gets the value of the finalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFinalName() {
            return finalName;
        }

        /**
         * Sets the value of the finalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFinalName(String value) {
            this.finalName = value;
        }

        /**
         * Gets the value of the midletType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMidletType() {
            return midletType;
        }

        /**
         * Sets the value of the midletType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMidletType(String value) {
            this.midletType = value;
        }

        /**
         * Gets the value of the shortUA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortUA() {
            return shortUA;
        }

        /**
         * Sets the value of the shortUA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortUA(String value) {
            this.shortUA = value;
        }

        /**
         * Gets the value of the userAgentKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserAgentKey() {
            return userAgentKey;
        }

        /**
         * Sets the value of the userAgentKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserAgentKey(String value) {
            this.userAgentKey = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="jadAction" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="action" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="add"/>
         *                       &lt;enumeration value="modify"/>
         *                       &lt;enumeration value="delete"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="inJad">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="signed"/>
         *                       &lt;enumeration value="unsigned"/>
         *                       &lt;enumeration value="always"/>
         *                       &lt;enumeration value="never"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="inMF">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="signed"/>
         *                       &lt;enumeration value="unsigned"/>
         *                       &lt;enumeration value="always"/>
         *                       &lt;enumeration value="never"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="strict" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "jadAction"
        })
        public static class JadAttributes {

            @XmlElement(required = true)
            protected List<JadAction> jadAction;

            /**
             * Gets the value of the jadAction property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the jadAction property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getJadAction().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JadAction }
             * 
             * 
             */
            public List<JadAction> getJadAction() {
                if (jadAction == null) {
                    jadAction = new ArrayList<JadAction>();
                }
                return this.jadAction;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="action" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="add"/>
             *             &lt;enumeration value="modify"/>
             *             &lt;enumeration value="delete"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="attribute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="inJad">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="signed"/>
             *             &lt;enumeration value="unsigned"/>
             *             &lt;enumeration value="always"/>
             *             &lt;enumeration value="never"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="inMF">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="signed"/>
             *             &lt;enumeration value="unsigned"/>
             *             &lt;enumeration value="always"/>
             *             &lt;enumeration value="never"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="strict" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class JadAction {

                @XmlAttribute(required = true)
                protected String action;
                @XmlAttribute(required = true)
                protected String attribute;
                @XmlAttribute
                protected String inJad;
                @XmlAttribute
                protected String inMF;
                @XmlAttribute
                protected Boolean strict;
                @XmlAttribute
                protected String value;

                /**
                 * Gets the value of the action property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAction() {
                    return action;
                }

                /**
                 * Sets the value of the action property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAction(String value) {
                    this.action = value;
                }

                /**
                 * Gets the value of the attribute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAttribute() {
                    return attribute;
                }

                /**
                 * Sets the value of the attribute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAttribute(String value) {
                    this.attribute = value;
                }

                /**
                 * Gets the value of the inJad property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInJad() {
                    return inJad;
                }

                /**
                 * Sets the value of the inJad property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInJad(String value) {
                    this.inJad = value;
                }

                /**
                 * Gets the value of the inMF property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInMF() {
                    return inMF;
                }

                /**
                 * Sets the value of the inMF property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInMF(String value) {
                    this.inMF = value;
                }

                /**
                 * Gets the value of the strict property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public boolean isStrict() {
                    if (strict == null) {
                        return false;
                    } else {
                        return strict;
                    }
                }

                /**
                 * Sets the value of the strict property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setStrict(Boolean value) {
                    this.strict = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }

}
