//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.15 at 08:59:21 AM CEST 
//


package com.orange.mmp.bind.data.branch;

import javax.xml.bind.annotation.XmlRegistry;
import com.orange.mmp.bind.data.branch.BranchCatalog.Branch;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orange.mmp.bind.data.branch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orange.mmp.bind.data.branch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Branch }
     * 
     */
    public Branch createBranchCatalogBranch() {
        return new Branch();
    }

    /**
     * Create an instance of {@link BranchCatalog }
     * 
     */
    public BranchCatalog createBranchCatalog() {
        return new BranchCatalog();
    }

}
