//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.26 at 11:44:05 AM CET 
//


package com.orange.mmp.core.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orange.mmp.core.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orange.mmp.core.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MMPConfig.Web.Accesspoint }
     * 
     */
    public MMPConfig.Web.Accesspoint createMMPConfigWebAccesspoint() {
        return new MMPConfig.Web.Accesspoint();
    }

    /**
     * Create an instance of {@link MMPConfig.Messagesource }
     * 
     */
    public MMPConfig.Messagesource createMMPConfigMessagesource() {
        return new MMPConfig.Messagesource();
    }

    /**
     * Create an instance of {@link MMPConfig.Fileset }
     * 
     */
    public MMPConfig.Fileset createMMPConfigFileset() {
        return new MMPConfig.Fileset();
    }

    /**
     * Create an instance of {@link MMPConfig }
     * 
     */
    public MMPConfig createMMPConfig() {
        return new MMPConfig();
    }

    /**
     * Create an instance of {@link MMPConfig.Api.Definition }
     * 
     */
    public MMPConfig.Api.Definition createMMPConfigApiDefinition() {
        return new MMPConfig.Api.Definition();
    }

    /**
     * Create an instance of {@link MMPConfig.Cache }
     * 
     */
    public MMPConfig.Cache createMMPConfigCache() {
        return new MMPConfig.Cache();
    }

    /**
     * Create an instance of {@link MMPConfig.Web }
     * 
     */
    public MMPConfig.Web createMMPConfigWeb() {
        return new MMPConfig.Web();
    }

    /**
     * Create an instance of {@link MMPConfig.Logger }
     * 
     */
    public MMPConfig.Logger createMMPConfigLogger() {
        return new MMPConfig.Logger();
    }

    /**
     * Create an instance of {@link MMPConfig.Api.Implementation }
     * 
     */
    public MMPConfig.Api.Implementation createMMPConfigApiImplementation() {
        return new MMPConfig.Api.Implementation();
    }

    /**
     * Create an instance of {@link MMPConfig.Api }
     * 
     */
    public MMPConfig.Api createMMPConfigApi() {
        return new MMPConfig.Api();
    }

    /**
     * Create an instance of {@link MMPConfig.MessageListener }
     * 
     */
    public MMPConfig.MessageListener createMMPConfigMessageListener() {
        return new MMPConfig.MessageListener();
    }

    /**
     * Create an instance of {@link MMPConfig.Filter }
     * 
     */
    public MMPConfig.Filter createMMPConfigFilter() {
        return new MMPConfig.Filter();
    }

    /**
     * Create an instance of {@link MMPConfig.Homepage }
     * 
     */
    public MMPConfig.Homepage createMMPConfigHomepage() {
        return new MMPConfig.Homepage();
    }

}
